"""
employee.py

Responsible for all employee-related operations:
- Adding, viewing, searching, updating, and deleting employees.
- Validating user input (required fields, email format, salary, ID).

Every function here receives an already-connected Supabase client (conn)
from main.py. Supabase queries return a response object with a `.data`
attribute (a list of dicts) -- rows are dicts, e.g. record['name'].

IMPORTANT: the 'employees' table's id column is auto-generated by
Postgres (see supabase_setup.sql). You never type an ID when adding an
employee -- Supabase assigns it and hands it back after insert.
"""

import re

EMAIL_PATTERN = r'^[\w\.-]+@[\w\.-]+\.\w+$'
TABLE = "employees"


# ---------------------------------------------------------------------
# Input validation helpers
# ---------------------------------------------------------------------

def get_non_empty_input(prompt):
    """Keeps asking until the user types something that isn't blank."""
    while True:
        value = input(prompt).strip()
        if value:
            return value
        print("This field cannot be empty. Please try again.")


def validate_email(email):
    """Returns True if the email matches a basic valid email pattern."""
    return re.match(EMAIL_PATTERN, email) is not None


def get_valid_email(current_email=None):
    """
    Keeps asking until a valid email is entered.
    If current_email is given, pressing Enter keeps that value (used for updates).
    """
    while True:
        if current_email:
            email = input(f"Enter new Email [{current_email}]: ").strip() or current_email
        else:
            email = input("Enter Email: ").strip()

        if validate_email(email):
            return email
        print("Invalid email format. Example: name@example.com")


def get_valid_salary(current_salary=None):
    """
    Keeps asking until a valid, non-negative number is entered.
    If current_salary is given, pressing Enter keeps that value (used for updates).
    """
    while True:
        if current_salary is not None:
            salary_str = input(f"Enter new Salary [{current_salary}]: ").strip()
            if salary_str == "":
                return current_salary
        else:
            salary_str = input("Enter Salary: ").strip()

        try:
            salary = float(salary_str)
            if salary < 0:
                print("Salary cannot be negative. Please try again.")
                continue
            return salary
        except ValueError:
            print("Invalid salary. Please enter a numeric value (e.g. 25000 or 25000.50).")


def get_valid_employee_id(prompt="Enter Employee ID: "):
    """
    Employee IDs are auto-generated whole numbers, so we validate that
    the user typed digits before ever querying the database with them.
    """
    while True:
        id_str = input(prompt).strip()
        if id_str.isdigit():
            return int(id_str)
        print("Invalid Employee ID. Please enter a whole number (e.g. 1, 2, 3).")


def print_employee_details(record):
    """Prints a single employee's full details. 'record' is a dict."""
    print("-" * 40)
    print(f"Employee ID   : {record['id']}")
    print(f"Name          : {record['name']}")
    print(f"Email         : {record['email']}")
    print(f"Phone         : {record['phone']}")
    print(f"Department    : {record['department']}")
    print(f"Designation   : {record['designation']}")
    print(f"Salary        : {float(record['salary']):.2f}")
    print("-" * 40)


# ---------------------------------------------------------------------
# Core features
# ---------------------------------------------------------------------

def add_employee(conn):
    """Prompts for employee details and inserts a new record.
    The Employee ID is NOT entered by the user -- Supabase assigns it."""
    print("\n--- Add New Employee ---")
    try:
        name = get_non_empty_input("Enter Employee Name: ")
        email = get_valid_email()
        phone = get_non_empty_input("Enter Phone Number: ")
        department = get_non_empty_input("Enter Department: ")
        designation = get_non_empty_input("Enter Designation: ")
        salary = get_valid_salary()

        # Supabase's client builds the request safely under the hood --
        # we never hand-build SQL strings, so this cannot be SQL-injected.
        response = conn.table(TABLE).insert({
            "name": name,
            "email": email,
            "phone": phone,
            "department": department,
            "designation": designation,
            "salary": salary,
        }).execute()

        new_id = response.data[0]["id"] if response.data else "unknown"
        print(f"Employee '{name}' added successfully. Employee ID: {new_id}")

    except Exception as e:
        print(f"Error while adding employee: {e}")


def view_all_employees(conn):
    """Displays every employee record in a readable table."""
    print("\n--- All Employees ---")
    try:
        response = conn.table(TABLE).select("*").order("id").execute()
        rows = response.data

        if not rows:
            print("No employee records found.")
            return

        header = f"{'ID':<6}{'Name':<18}{'Email':<25}{'Phone':<15}{'Department':<15}{'Designation':<15}{'Salary':<10}"
        print(header)
        print("-" * len(header))

        for r in rows:
            print(f"{r['id']:<6}{r['name']:<18}{r['email']:<25}{r['phone']:<15}"
                  f"{r['department']:<15}{r['designation']:<15}{float(r['salary']):<10.2f}")

    except Exception as e:
        print(f"Error while fetching employees: {e}")


def search_employee(conn):
    """Searches for employees by ID (exact) or by name (partial match)."""
    print("\n--- Search Employee ---")
    print("1. Search by Employee ID")
    print("2. Search by Name")
    choice = input("Enter your choice: ").strip()

    try:
        if choice == "1":
            emp_id = get_valid_employee_id()
            response = conn.table(TABLE).select("*").eq("id", emp_id).execute()
        elif choice == "2":
            name = get_non_empty_input("Enter Employee Name: ")
            # ilike = case-insensitive LIKE; %..% matches anywhere in the name.
            response = conn.table(TABLE).select("*").ilike("name", f"%{name}%").execute()
        else:
            print("Invalid choice. Please enter 1 or 2.")
            return

        rows = response.data
        if not rows:
            print("No matching employee found.")
            return

        for r in rows:
            print_employee_details(r)

    except Exception as e:
        print(f"Error while searching: {e}")


def update_employee(conn):
    """
    Updates an existing employee's details, found by ID.
    Pressing Enter on any field keeps its current value.
    """
    print("\n--- Update Employee ---")
    try:
        emp_id = get_valid_employee_id("Enter Employee ID to update: ")
        response = conn.table(TABLE).select("*").eq("id", emp_id).execute()
        rows = response.data

        if not rows:
            print(f"No employee found with ID {emp_id}.")
            return

        record = rows[0]
        print("Current details:")
        print_employee_details(record)
        print("Press Enter on any field to keep its current value.\n")

        name = input(f"Enter new Name [{record['name']}]: ").strip() or record['name']
        email = get_valid_email(record['email'])
        phone = input(f"Enter new Phone [{record['phone']}]: ").strip() or record['phone']
        department = input(f"Enter new Department [{record['department']}]: ").strip() or record['department']
        designation = input(f"Enter new Designation [{record['designation']}]: ").strip() or record['designation']
        salary = get_valid_salary(float(record['salary']))

        conn.table(TABLE).update({
            "name": name,
            "email": email,
            "phone": phone,
            "department": department,
            "designation": designation,
            "salary": salary,
        }).eq("id", emp_id).execute()

        print("Employee updated successfully.")

    except Exception as e:
        print(f"Error while updating employee: {e}")


def delete_employee(conn):
    """Deletes an employee by ID, after asking for confirmation."""
    print("\n--- Delete Employee ---")
    try:
        emp_id = get_valid_employee_id("Enter Employee ID to delete: ")
        response = conn.table(TABLE).select("*").eq("id", emp_id).execute()
        rows = response.data

        if not rows:
            print(f"No employee found with ID {emp_id}.")
            return

        print_employee_details(rows[0])
        confirm = input("Are you sure you want to delete this employee? (yes/no): ").strip().lower()

        if confirm == "yes":
            conn.table(TABLE).delete().eq("id", emp_id).execute()
            print("Employee deleted successfully.")
        else:
            print("Delete cancelled.")

    except Exception as e:
        print(f"Error while deleting employee: {e}")